name: 'Search a string in github organization'
description: 'Search a string in github organization'
inputs:
  gthub-org-name:
    description: 'Github orhanization name'
    required: true
    default: ''
  gthub-token:
    description: 'Github service account token'
    required: true
    default: ''
  search-string:
    description: 'Search string'
    required: true
    default: ''
  file-extension:
    description: 'Extension of file to be searched in'
    required: false
    default: ''

runs:
  using: 'node16'
  main: 'index.js'
