name: Search String in Github Org

on:
  workflow_dispatch:
    inputs:
      searchString:
        description: 'Enter Search String'     
        required: true
        default: ''
      fileExtension:
        description: 'Enter File Extension'     
        required: false
        default: ''

jobs:
  SearchString:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout pipeline repo'
        uses: actions/checkout@v3

      - name: search the string in github organization
        uses: ./.github/actions/search-string-in-github-org
        with:
          gthub-org-name: 'PipelineTest-VP'
          gthub-token: ${{ secrets.GTHUB_TOKEN }}
          search-string: ${{ github.event.inputs.searchString }}
          file-extension: ${{ github.event.inputs.fileExtension }}